---
- name: docker playbook
  hosts: all
  become: true
  tasks:
    - name: docker installation
      apt:
        update_cache: yes
        name: docker.io
        state: present

    - name: copy dockerfile to remote ansible machine
      copy:
        src: /var/lib/jenkins/workspace/ansibledocker/Dockerfile
        dest: /home/ubuntu/

    - name: docker image creation
      docker_image:
        name: net1
        source: build
        build:
          path: /home/ubuntu/
          pull: false

    - name : docker container creation
      docker_container:
        name: cs4
        image: net1
        detach: true
        state: started
        tty: true
        exposed_ports:
        - "80"
        ports:
        - "80:80"
